---
abstract: 'Store multiple boolean fields in one integer field'
author:
  - 'Moritz Onken <onken@netcubed.de>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092071'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-BitField
requires:
  DBD::SQLite: 0
  DBIx::Class: 0.08107
  File::Find::Rule: 0
  Test::More: 0.92
resources:
  repository: http://github.com/monken/DBIx-Class-BitField/tree
version: 0.13
