---
abstract: 'Store multiple boolean fields in one integer field'
author:
  - 'Moritz Onken <onken@netcubed.de>'
build_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.86'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-BitField
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.08102
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/monken/DBIx-Class-BitField/tree/master
version: 0.00_01
